In [2]:
import numpy as np

W1 = np.random.randn(2,4) # 가중치
b1 = np.random.randn(4) # 편향
x = np.random.randn(10,2) # 입력
h = np.matmul(x, W1) + b1 

print(h)

[[-0.72273842 -0.65789082 -0.48837368  0.50691894]
 [ 1.99655348  0.02906224  1.32098995 -0.09108849]
 [ 1.15404884  0.00746754  0.14777922  0.74366796]
 [ 0.98983823  0.02198952 -0.14089171  0.96998122]
 [-2.88975931 -1.54787869 -0.83293189 -0.17987358]
 [ 4.32895162  1.03910056  1.52484687  0.82515948]
 [ 0.90799254 -0.32859457  0.86148532 -0.13243234]
 [ 1.94223089  0.12836064  0.92278898  0.30469402]
 [ 4.33984156  1.08031531  1.40887723  0.95339261]
 [-1.38437132 -1.23864846  0.39637181 -0.75227063]]


In [3]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))  ## numpy에 exp 함수가 존재. exp(-x)는 e^-x를 의미함

x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

print(s)

[[ 1.50452507 -0.85021278 -2.9772356 ]
 [ 1.18139191 -0.62095855 -3.00584143]
 [ 1.20809046  0.14062824 -2.79147824]
 [ 1.59144565 -0.38450935 -2.94094348]
 [ 2.02233648 -1.44289629 -2.73900788]
 [ 0.46257682  0.02100689 -2.99946488]
 [ 2.01064265 -1.02982713 -2.84908841]
 [ 2.04178839 -0.56638037 -2.93445444]
 [ 1.4245603  -1.13288154 -3.02037155]
 [ 1.84669652 -0.4726187  -2.94199029]]


In [ ]:
class Sigmoid:    # 시그모이드 계층
    def __init__(self):
        self.params = []
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))
    
class Affine:     # Affine 계층
    def __init__(self, W, b):       
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b
        return out
    
class TwoLayerNet:    # 2층 신경망
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        # 가중치와 편향 초기화 (파라미터 초기화)
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 모든 가중치를 리스트에 모은다. (각 계층의 params를 리스트에 추가하는 코드)
        self.params = []
        for layer in self.layers:
            self.params += layer.params
    
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    

## SGD 구현 (p.28)  -- 미니 배치 데이터 미입력됨

In [ ]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr
        
    def update(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr * grads[i]

model = TwoLayerNet(2, 4, 3)   # input_size=2, hidden_size=4, output_size=3으로 설정 / # 입력 크기: 2 -> 은닉층 크기: 4 -> 출력 크기: 3 (교재엔 ...으로 되어있음)
optimizer = SGD()

for i in range(10000):  # 반복 횟수 설정
    """미니 배치 설정 생략됨"""
    x_batch, t_batch = get_mini_batch(...)  # 미니배치 데이터 가져오기
    loss = model.forward(x_batch, t_batch)  # 순전파로 손실 계산
    model.backward()  # 역전파로 기울기 계산
    optimizer.update(model.params, model.grads)  # SGD로 매개변수 갱신

NameError: name 'get_mini_batch' is not defined