In [ ]:
import numpy as np

W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])

print(W + X)

[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
print(W * X)

[[ 0  2  6]
 [12 20 30]]


In [5]:
import numpy as np

W1 = np.random.randn(2,4) # 가중치
b1 = np.random.randn(4) # 편향
x = np.random.randn(10,2) # 입력
h = np.matmul(x, W1) + b1